fixed a typo in run-actions.ts
mrjones2014/yaclt pull request #132
Opened 2021-09-09 18:29 UTC by demonicirfan

Resolves: #132 

## How to Test

1. Just make sure the build passes, its just renaming a function, so as long as typescript compiles we should be good

## Changelog

correct the spellings of function `relativize` which was `relativeize` before. Also, update the name where the function was called.

2021-09-09 18:35 UTC, mrjones2014 commented
@demonicirfan you changed the function call typo but not where it's defined. You'll need to change it both places.

Also, please fill out the PR template.

2021-09-09 18:57 UTC, mrjones2014 requested changes

2021-09-09 18:57 UTC, mrjones2014 commented on src/utils/run-action.ts
> +      Logger.info(`Using configuration file at ${relativize(configPath)}`);
you'll need to change it where the function is declared as well.

2021-09-09 21:26 UTC, mrjones2014 commented
@demonicirfan code looks good, just fill out the PR template and I'll merge. 
![image](https://user-images.githubusercontent.com/8648891/132764930-1ed0c41c-57ce-46b6-bfca-4321042d6a2c.png)

2021-09-09 21:28 UTC, mrjones2014 commented
You also need to add a changelog. Please see [CONTRIBUTING.md](https://github.com/mrjones2014/yaclt/blob/master/CONTRIBUTING.md)

2021-09-10 04:03 UTC, demonicirfan commented
I have gone through the contributors.md  I don't know what to write under HOW TO TEST section so i just added issue number in template. Please guide me if there is something which i should do

2021-09-10 11:04 UTC, mrjones2014 commented
@demonicirfan no worries, I've added the testing instructions for you. Last thing you need to do is add a changelog.

Instructions for this are in CONTRIBUTING.md.

2021-09-10 15:16 UTC, demonicirfan commented
I have never done this changelog and test thing before i don't have much idea about changelog i have update the above text.

2021-09-10 15:20 UTC, mrjones2014 commented
@demonicirfan just run:

```
yarn
yarn build
./dist/index.js new
```

Then edit the generated file and add it to this PR.

2021-09-10 16:44 UTC, demonicirfan commented
Ok, I understood thanks for explaining to me. I have pushed the changelog now, have I done it right.

2021-09-10 17:40 UTC, mrjones2014 commented
@demonicirfan You should use the CLI to generate your changelog file, then fill in the details. Please read the `README.md` and `CONTRIBUTING.md`. Basically what you want to do is:

```
yarn build
./dist/index.js new
```

Then fill in the details. Alternatively you can fill in the details from the command line by doing 
```
yarn build
./dist/index.js new --changeType IMPROVED -m "Your message here"
```

2021-09-10 18:55 UTC, hsheikhali1 commented on changelogs/2021-09-10T22-09-11.358+05-30.md
> +Correct the spellings of function `relativize` which was `relativeize` before. Also, update the name where the function was called.
Hey @demonicirfan -- your changelog entry is incorrect here. The `CONTRIBUTING.md` file describes how this should look. Once you read through the CONTRIBUTING.md file can you re-commit this changelog entry? 👍🏽

2021-09-10 20:15 UTC, mrjones2014 commented on changelogs/2021-09-10T22-09-11.358+05-30.md
> +Correct the spellings of function `relativize` which was `relativeize` before. Also, update the name where the function was called.
It should end up looking something like:

```
[IMPROVED] Fix typo in function name, change `relativeize` to `relativize` {#132}
```

2021-09-11 02:54 UTC, demonicirfan commented on changelogs/2021-09-10T22-09-11.358+05-30.md
> +Correct the spellings of function `relativize` which was `relativeize` before. Also, update the name where the function was called.
ok

2021-09-11 16:00 UTC, mrjones2014 approved these changes

2021-09-12 14:32 UTC, merged

2021-09-12 15:04 UTC, mrjones2014 commented
@demonicirfan in the future please be sure to link the issue number, not the PR number, in your PR description and changelog entry.