Vishal/137 updated pr template
mrjones2014/yaclt pull request #140
Opened 2021-09-10 14:47 UTC by vishal-codes

Resolves: #134 

## How to Test
Check out the `pull_request_template.md` file

## Potential Side Effects/Things to Look Out For
NO Potential Side Effects

2021-09-10 14:53 UTC, mrjones2014 requested changes

2021-09-10 14:53 UTC, mrjones2014 commented on changelogs/2021-09-10T20-11-51.999+05-30.md
> +[NEW] A user-friendly description of your change {#137}
This should be `[IMPROVED]` and provide a description of your change -- this is the default placeholder changelog.

2021-09-10 14:56 UTC, vishal-codes commented on changelogs/2021-09-10T20-11-51.999+05-30.md
> +[NEW] A user-friendly description of your change {#137}
ohh okaay

2021-09-10 16:27 UTC, vishal-codes commented on changelogs/2021-09-10T20-11-51.999+05-30.md
> +[NEW] A user-friendly description of your change {#137}
Done  !! @mrjones2014

2021-09-10 16:30 UTC, mrjones2014 commented on changelogs/2021-09-10T20-11-51.999+05-30.md
> +Upadated PR template to make sure people are reading the contributing guidelines. Made changes in the pull_request_template.md file.
I meant like this:

```suggestion
[IMPROVED] Upadated PR template to make sure people are reading the contributing guidelines. {#137}
```

Please read through the `README.md`, `COMMANDS.md`, and `CONTRIBUTING.md` to get an understanding of how the CLI works.

2021-09-10 16:31 UTC, mrjones2014 commented on changelogs/2021-09-10T20-11-51.999+05-30.md
> +Upadated PR template to make sure people are reading the contributing guidelines. Made changes in the pull_request_template.md file.
I've added it for you this time.

2021-09-10 16:32 UTC, mrjones2014 approved these changes

2021-09-10 16:32 UTC, merged

2021-09-10 16:35 UTC, vishal-codes commented
@mrjones2014 should I delete the branch?

2021-09-10 16:36 UTC, mrjones2014 commented
@vishal-codes your choice. Your branch only exists in your fork. The PR was merged into master in this repo.

2021-09-10 22:27 UTC, mrjones2014 commented
@vishal-codes please consider starring the repo if you like it :)

2021-09-12 14:34 UTC, mrjones2014 commented
@vishal-codes please make sure you link the correct issue next time. This had unintentionally closed an issue that this PR did not resolve.