Updated bug issue template
mrjones2014/yaclt pull request #157
Opened 2021-09-13 12:43 UTC by vishal-codes

Resolves: #149 

## How to Test
Checkout the updated file

## Potential Side Effects/Things to Look Out For
NO potential side effects

2021-09-13 12:55 UTC, mrjones2014 requested changes

2021-09-13 12:55 UTC, mrjones2014 commented on .github/ISSUE_TEMPLATE/bug_report.md
> ----
Ah okay I think this is markdown front matter we can use to set attributes on the issue.

Can we add back:

```
---
labels: 'bug'
---
```

2021-09-13 12:55 UTC, mrjones2014 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- OS: [e.g. iOS/ android/ macOS/ Linux/ Windows]
```suggestion
- OS: [e.g. macOS/Linux/Windows]
```

it's a command line tool so it doesn't support mobile devices

2021-09-13 12:55 UTC, mrjones2014 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- Device: [e.g. Desktop, Pixel 4a, iPhone6]
```suggestion
```

We only support desktop devices since its a command line tool

2021-09-13 12:55 UTC, mrjones2014 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- Browser-Version [e.g. 22]
```suggestion
```

browser is irrelevant since its a command line tool

2021-09-13 12:55 UTC, mrjones2014 commented on changelogs/2021-09-13T18-10-07.416+05-30.md
> +[IMPROVED] Update bug issue template by removing irrelevant prompts. {#149}
```suggestion
[IMPROVED] Update bug issue template to remove irrelevant prompts {#149}
```

2021-09-16 13:30 UTC, vishal-codes commented on .github/ISSUE_TEMPLATE/bug_report.md
> ----
Can I get some more info about this? Do you want the top part something like this?
![Screenshot from 2021-09-16 18-58-48](https://user-images.githubusercontent.com/79784161/133620963-7359239a-8a5b-429b-a156-4bd3f1f5227c.png)

2021-09-16 13:30 UTC, mrjones2014 requested changes

2021-09-16 13:30 UTC, mrjones2014 commented on .github/ISSUE_TEMPLATE/bug_report.md
Let's also add `- yaclt version: `

2021-09-16 13:32 UTC, vishal-codes commented on .github/ISSUE_TEMPLATE/bug_report.md
where do you want it?

2021-09-16 13:37 UTC, mrjones2014 commented on .github/ISSUE_TEMPLATE/bug_report.md
> ----
The top part won't actually appear when rendered in the issue, it's basically a way to tell GitHub "when using this template, apply the bug label automatically".

It's called front matter: https://assemble.io/docs/YAML-front-matter.html

2021-09-16 13:37 UTC, mrjones2014 commented on .github/ISSUE_TEMPLATE/bug_report.md
Above or below the `- OS:` line.

2021-09-16 13:53 UTC, vishal-codes commented on .github/ISSUE_TEMPLATE/bug_report.md
> ----
Ohh okay

2021-09-16 14:15 UTC, mrjones2014 approved these changes
Looks great.

2021-09-16 14:15 UTC, merged