#131 - changed PrepareReleaseStrategy class to an interface
mrjones2014/yaclt pull request #162
Opened 2021-09-14 23:56 UTC by hsheikhali1

Resolves: #131 

## How to Test

1. Run `git checkout master && git pull`
2. Once you have the latest and the greatest; run `git checkout -b hsheikhali1-hsheikhali/131-change-class-to-interface`
3. Run `git pull https://github.com/hsheikhali1/yaclt.git hsheikhali/118-move-package-to-dev-deps`
4. run `yarn` to install dependencies
5. run `yarn build && ./dist/index.js new --changeType "IMPROVED"` to see if `yaclt` can still generate new changelog entries.

2021-09-14 23:57 UTC, hsheikhali1 commented
@mrjones2014 let me know if I got the test instructions right this time

2021-09-15 11:03 UTC, mrjones2014 commented
> @mrjones2014 let me know if I got the test instructions right this time

I'm guessing the branch name you listed is wrong?

>hsheikhali/118-move-package-to-dev-deps

2021-09-15 11:05 UTC, mrjones2014 commented
Also, @hsheikhali1 not a big deal this time, but whatever email address you're using to make these commits is not associated with your GitHub account. Notice how there's no profile link.

![CleanShot-2021-09-15-at-07 05 03](https://user-images.githubusercontent.com/8648891/133422429-6adb3f5f-08fd-4149-b14f-9c37d644b7b9.png)

2021-09-15 11:07 UTC, mrjones2014 requested changes
Small nit in the changelog entry.

2021-09-15 11:07 UTC, mrjones2014 commented on changelogs/2021-09-14T19-26-47.533-04-00.md
> +[IMPROVED] Change `PrepareReleaseStrategy` class to an interface {#131}
```suggestion
[IMPROVED] Change `PrepareReleaseStrategy` abstract class to an interface {#131}
```

2021-09-15 11:11 UTC, mrjones2014 commented
Found the correct branch under the PR title. Tested the build. Looks Good aside from the one comment I made on the changelog entry.

2021-09-25 22:44 UTC, mrjones2014 commented
@hsheikhali1 this PR has been sitting here a while. Let me know if you need me to bring it over the finish line.

2021-09-25 22:54 UTC, hsheikhali1 commented
Oh let me take a look when I get home

2021-09-26 02:18 UTC, mrjones2014 approved these changes

2021-09-26 02:18 UTC, merged