Srimathi s/30 add unit tests using jest 30
mrjones2014/yaclt pull request #176
Opened 2021-10-03 13:42 UTC by Srimathi-S

Resolves: #30 

## How to Test

Use 'yarn run' in cli to verify the added tests for two files in utils

## Potential Side Effects/Things to Look Out For

1) New dependency of "jest" along with "@types/jest" and "ts-jest" got added
2) Relying on code as source of truth tests were added so please look out that behaviour is properly tested

2021-10-03 16:37 UTC, mrjones2014 requested changes
@Srimathi-S this looks pretty good! Mostly left some minor feedback.

One more thing, can we run tests in CI? To do this, you will need to just add a `yarn test` line to both `.github/workflows/build.yml` and `.github/workflows/publish.yml`. The `yarn test` line should probably come right after the `yarn build` one.

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +  test("should return 5 when the regular expression is satisfied at the 4th index", () => {
I'm a bit confused by this test.

the `-` occurs at index 6. shouldn't this return 6? (there may be a bug in the implementation of `regexIndexOf` that this test reveals).

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    expect(actual).toBe(expected);
can we use `toBeUndefined()` here instead for readability?

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let expected = undefined;
this line can be removed if we use `.toBeUndefined()` matcher below.

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let actual = formatToChangeTypeTemplate("nothing in place");
```suggestion
    const actual = formatToChangeTypeTemplate("nothing in place");
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let expected = -1;
```suggestion
    const expected = -1;
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let actual = regexIndexOf("hello-r", RegExp("^r"), 1);
```suggestion
    const actual = regexIndexOf("hello-r", RegExp("^r"), 1);
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let expected = 1;
```suggestion
    const expected = 1;
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let actual = regexIndexOf("hello-r", RegExp("^e"), 1);
```suggestion
    const actual = regexIndexOf("hello-r", RegExp("^e"), 1);
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let expected = 5;
```suggestion
    const expected = 5;
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let actual = regexIndexOf("hello-r", RegExp("-"), 1);
```suggestion
    const actual = regexIndexOf("hello-r", RegExp("-"), 1);
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let expected = "";
```suggestion
    const expected = "";
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let actual = camelToKebabCase("");
```suggestion
    const actual = camelToKebabCase("");
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let expected = "hello-world";
```suggestion
    const expected = "hello-world";
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let actual = camelToKebabCase("helloWorld");
```suggestion
    const actual = camelToKebabCase("helloWorld");
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let expected = "hello";
```suggestion
    const expected = "hello";
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let actual = camelToKebabCase("hello");
```suggestion
    const actual = camelToKebabCase("hello");
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let expected = "";
```suggestion
    const expected = "";
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let actual = kebabToCamelCase("");
```suggestion
    const actual = kebabToCamelCase("");
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let expected = "helloWorld";
```suggestion
    const expected = "helloWorld";
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let actual = kebabToCamelCase("hello-World");
```suggestion
    const actual = kebabToCamelCase("hello-World");
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let expected = "helloWorld";
```suggestion
    const expected = "helloWorld";
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let actual = kebabToCamelCase("hello-world");
```suggestion
    const actual = kebabToCamelCase("hello-world");
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let expected = "hello";
```suggestion
    const expected = "hello";
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +    let actual = camelToKebabCase("hello");
```suggestion
    const actual = camelToKebabCase("hello");
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/template-utils.test.ts
> +    let options: CompileOptions = { noEscape: true };
```suggestion
    const template = "hello";
    const options: CompileOptions = { noEscape: true };
```

2021-10-03 16:37 UTC, mrjones2014 commented on src/utils/template-utils.test.ts
> +    let inputOptions: CompileOptions = { strict: true };
```suggestion
    const template = "hello";
    const options: CompileOptions = { noEscape: true, strict: true };
    const inputOptions: CompileOptions = { strict: true };
```

2021-10-03 16:37 UTC, mrjones2014 commented
Tag me when you're ready for another review on this PR @Srimathi-S !

2021-10-03 16:39 UTC, mrjones2014 commented
And please consider starring the repo if you like it!

2021-10-04 01:57 UTC, Srimathi-S commented on src/utils/string-utils.test.ts
> +  test("should return 5 when the regular expression is satisfied at the 4th index", () => {
There is no issue it returns 5 because the starting position is 1. Will consider renaming this method to be more clear. Also I will be doing all the changes suggested and submit for review again

2021-10-04 02:33 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +  test("should return 5 when the regular expression is satisfied at the 4th index", () => {
Hm.. shouldn’t it return an index? So shouldn’t the starting position be 0?

2021-10-04 03:24 UTC, Srimathi-S commented
@mrjones2014 made changes in pr please review again now

2021-10-04 03:29 UTC, Srimathi-S commented on src/utils/string-utils.test.ts
> +  test("should return 5 when the regular expression is satisfied at the 4th index", () => {
It accepts starting position as parameter and the value passed in the test is 1 which means it starts from second character

2021-10-04 10:33 UTC, mrjones2014 commented on src/utils/string-utils.test.ts
> +  test("should return 5 when the regular expression is satisfied at the 4th index", () => {
Ohh gotcha. Looking at the docs for regular `String.indexOf` it appears this works the same way. Thanks for clarifying.

http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf

2021-10-04 10:35 UTC, mrjones2014 approved these changes
Awesome! This is a great first pass! Looking forward to seeing more!

2021-10-04 10:38 UTC, merged