#61 - fix default changelog template
mrjones2014/yaclt pull request #65
Opened 2021-07-22 13:45 UTC by hsheikhali1

## What Changed
* default template now has a line break at the end just before the next heading
*   Special characters are no longer HTML encoded when converting to markdown using Handlebars

## How to test
1. Pull this branch
2. build yactl
3. generate a new changelog with special characters and see the results

## Notes
None.

2021-07-22 14:18 UTC, mrjones2014 requested changes
Looks pretty good, need a couple minor changes. Also needs a changelog added.

2021-07-22 14:18 UTC, mrjones2014 commented on src/actions/prepare-release.ts
> +  const template = Handlebars.compile(options.template, { noEscape: true });
hmm. is there a way we can set this as a global option? if not, we should update all `Handlebars.compile` calls to use this option.

2021-07-22 14:18 UTC, mrjones2014 commented on src/cli/commands/prepare-release.ts
> +      default: `# Release {{releaseNumber}} - {{moment "YYYY-MM-DD"}}\n\n{{#each entryGroups}}## {{capitalize label}}\n\n{{#each items}}- {{this}}\n{{/each}}{{/each}}\n---\n&nbsp;`,
I don't think we need this `&nbsp;` 

I think what we need here is actually an additional `\n` in between the two `{{/each}}` at the end there -- this will put an extra newline between each category section like `## New` `## Improved` etc.

2021-07-22 14:18 UTC, mrjones2014 commented on CHANGELOG.md
> +&nbsp;
yeah I think this is from the `&nbsp;` in the template you added.

2021-07-22 14:54 UTC, hsheikhali1 commented on src/actions/prepare-release.ts
> +  const template = Handlebars.compile(options.template, { noEscape: true });
interesting -- I'm sure there is a way let me dig in a bit more

2021-07-22 14:55 UTC, hsheikhali1 commented on src/cli/commands/prepare-release.ts
> +      default: `# Release {{releaseNumber}} - {{moment "YYYY-MM-DD"}}\n\n{{#each entryGroups}}## {{capitalize label}}\n\n{{#each items}}- {{this}}\n{{/each}}{{/each}}\n---\n&nbsp;`,
Yeah I tried to add `\n` at first and it did nothing but let me try after  {{/each}}

2021-07-23 21:24 UTC, mrjones2014 commented on CHANGELOG.md
> +# Release 0.5.3 - 2021-07-23
you can revert this file -- this gets updated for releases only

2021-07-24 04:08 UTC, hsheikhali1 commented on CHANGELOG.md
> +# Release 0.5.3 - 2021-07-23
done

2021-07-24 04:09 UTC, hsheikhali1 commented on src/actions/prepare-release.ts
> +  const template = Handlebars.compile(options.template, { noEscape: true });
Yeah I basically moved this out to its own util function like you suggested and replaced `Handlebars.compile` with `compile`

2021-07-24 15:29 UTC, mrjones2014 commented on src/utils/template-utils.ts
> +  const optionsWithDefaults = Object.assign({ noEscape: true }, options);
This looks really good. Can we rename the function `compileTemplate` so that it’s more obvious what it’s doing when imported into other modules?

2021-07-24 17:29 UTC, hsheikhali1 commented on src/utils/template-utils.ts
> +  const optionsWithDefaults = Object.assign({ noEscape: true }, options);
oh yeah for sure that makes total sense

btw, why are you using `Object.assign({})` instead of `options = { ...options, { noEscape: true }}` ?

2021-07-24 17:36 UTC, mrjones2014 commented on src/utils/template-utils.ts
> +  const optionsWithDefaults = Object.assign({ noEscape: true }, options);
Honestly, bad habit from a previous job. However, the `{ noEscape: true }` should come first in case we ever need to override it. But go ahead and change the syntax if you want.

2021-07-24 17:56 UTC, mrjones2014 commented
@hsheikhali1 this looks perfect now, merging.

2021-07-24 17:56 UTC, mrjones2014 approved these changes
looks great now.

2021-07-24 17:56 UTC, merged